#!/usr/bin/env python3
"""Fix cell 67 - replace estimators_best usage with individual parameters"""
import json

# Read notebook
with open('Heart_Disease_Analysis_Refactored.ipynb', 'r') as f:
    nb = json.load(f)

# Find the cell with "DETAILED EVALUATION MATRIX FOR BEST TEST SCENARIO"
for i, cell in enumerate(nb['cells']):
    if cell['cell_type'] == 'code':
        source = ''.join(cell.get('source', []))
        if 'DETAILED EVALUATION MATRIX FOR BEST TEST SCENARIO' in source and 'estimators_best' in source:
            print(f'Found cell {i+1} with problematic code')
            
            # Replace the old source with fixed source
            new_source = [
                "# ===== DETAILED EVALUATION MATRIX FOR BEST TEST SCENARIO =====\n",
                "print(\"🎯 DETAILED EVALUATION MATRIX - BEST TEST SCENARIO\")\n",
                "\n",
                "# Ambil info best scenario\n",
                "best_scenario_name = best_test_scenario['Scenario']\n",
                "print(f\"\\n✨ Best Scenario: {best_scenario_name}\")\n",
                "print(f\"Test Accuracy: {best_test_scenario['Test_Accuracy']:.6f} ({best_test_scenario['Test_Accuracy']*100:.2f}%)\")\n",
                "\n",
                "# Ambil konfigurasi terbaik untuk scenario ini\n",
                "df_scenario = df_cv_biasa[df_cv_biasa['Scenario'] == best_scenario_name]\n",
                "best_config = df_scenario.sort_values('Accuracy_Mean', ascending=False).iloc[0]\n",
                "\n",
                "# Extract parameters\n",
                "pcc_thresh_best = best_config['PCC_Threshold']\n",
                "chi2_k_best = best_config['Chi2_K']\n",
                "n_features_best = int(best_config['N_Features'])\n",
                "# Extract ETC parameters\n",
                "etc_n_estimators_best = int(best_config['ETC_n_estimators'])\n",
                "etc_max_features_best = best_config['ETC_max_features']\n",
                "etc_min_samples_split_best = int(best_config['ETC_min_samples_split'])\n",
                "etc_min_samples_leaf_best = int(best_config['ETC_min_samples_leaf'])\n",
                "etc_max_depth_best = int(best_config['ETC_max_depth'])\n",
                "etc_criterion_best = best_config['ETC_criterion']\n",
                "etc_class_weight_best = best_config['ETC_class_weight']\n",
                "etc_bootstrap_best = best_config['ETC_bootstrap']\n",
                "etc_random_state_best = int(best_config['ETC_random_state'])\n",
                "# Extract XGB parameters\n",
                "xgb_n_estimators_best = int(best_config['XGB_n_estimators'])\n",
                "xgb_learning_rate_best = float(best_config['XGB_learning_rate'])\n",
                "xgb_max_depth_best = int(best_config['XGB_max_depth'])\n",
                "xgb_colsample_bytree_best = float(best_config['XGB_colsample_bytree'])\n",
                "xgb_subsample_best = float(best_config['XGB_subsample'])\n",
                "xgb_random_state_best = int(best_config['XGB_random_state'])\n",
                "\n",
                "# Feature Selection (recreate the best model)\n",
                "pcc_selected_features = []\n",
                "chi2_selected_features = []\n",
                "\n",
                "# 1. PCC untuk fitur numerik\n",
                "if pd.notna(pcc_thresh_best) and best_scenario_name in ['Pcc', 'Combined']:\n",
                "    X_numerik = X_train_final[FITUR_NUMERIK]\n",
                "    pcc_scores = {}\n",
                "    for col in X_numerik.columns:\n",
                "        corr = X_numerik[col].corr(y_train_final)\n",
                "        pcc_scores[col] = abs(corr)\n",
                "    pcc_selected_features = [f for f, score in pcc_scores.items() if score >= pcc_thresh_best]\n",
                "\n",
                "# 2. Chi2 untuk fitur kategorikal\n",
                "if pd.notna(chi2_k_best) and best_scenario_name in ['Chi2', 'Combined']:\n",
                "    X_kategorikal = X_train_final[FITUR_KATEGORIKAL]\n",
                "    chi2_selector = SelectKBest(chi2, k=int(chi2_k_best))\n",
                "    chi2_selector.fit(X_kategorikal, y_train_final)\n",
                "    chi2_m = chi2_selector.get_support()\n",
                "    chi2_selected_features = [FITUR_KATEGORIKAL[i] for i in range(len(FITUR_KATEGORIKAL)) if chi2_m[i]]\n",
                "\n",
                "# 3. Pilih fitur sesuai scenario\n",
                "if best_scenario_name == 'Baseline':\n",
                "    selected_features = list(X_train_final.columns)\n",
                "elif best_scenario_name == 'Pcc':\n",
                "    selected_features = pcc_selected_features + FITUR_KATEGORIKAL\n",
                "elif best_scenario_name == 'Chi2':\n",
                "    selected_features = FITUR_NUMERIK + chi2_selected_features\n",
                "elif best_scenario_name == 'Combined':\n",
                "    selected_features = pcc_selected_features + chi2_selected_features\n",
                "\n",
                "# Train model dengan konfigurasi terbaik\n",
                "X_train_selected = X_train_final[selected_features]\n",
                "X_test_selected = X_test_final[selected_features]\n",
                "\n",
                "model_final = ETCXGBHybrid(\n",
                "    etc_n_estimators=etc_n_estimators_best,\n",
                "    etc_max_features=etc_max_features_best,\n",
                "    etc_min_samples_split=etc_min_samples_split_best,\n",
                "    etc_min_samples_leaf=etc_min_samples_leaf_best,\n",
                "    etc_max_depth=etc_max_depth_best,\n",
                "    etc_criterion=etc_criterion_best,\n",
                "    etc_class_weight=etc_class_weight_best,\n",
                "    etc_bootstrap=etc_bootstrap_best,\n",
                "    etc_random_state=etc_random_state_best,\n",
                "    xgb_n_estimators=xgb_n_estimators_best,\n",
                "    xgb_learning_rate=xgb_learning_rate_best,\n",
                "    xgb_max_depth=xgb_max_depth_best,\n",
                "    xgb_colsample_bytree=xgb_colsample_bytree_best,\n",
                "    xgb_subsample=xgb_subsample_best,\n",
                "    xgb_random_state=xgb_random_state_best\n",
                ")\n",
                "model_final.fit(X_train_selected, y_train_final)\n",
                "\n",
                "# Prediksi pada test set\n",
                "y_pred_test = model_final.predict(X_test_selected)\n",
                "y_pred_proba = model_final.predict_proba(X_test_selected)[:, 1]\n",
                "\n",
                "# ===== MODEL CONFIGURATION SUMMARY =====\n",
                "print(\"⚙️ MODEL CONFIGURATION SUMMARY\")\n",
                "config_summary = {\n",
                "    'Parameter': ['Scenario', 'PCC Threshold', 'Chi2 K', 'ETC n_estimators', 'ETC max_features', 'XGB n_estimators', 'XGB learning_rate', 'Number of Features', 'Selected Features'],\n",
                "    'Value': [best_scenario_name, pcc_thresh_best if pd.notna(pcc_thresh_best) else 'N/A', int(chi2_k_best) if pd.notna(chi2_k_best) else 'N/A', etc_n_estimators_best, etc_max_features_best, xgb_n_estimators_best, xgb_learning_rate_best, len(selected_features), ', '.join(selected_features)]\n",
                "}\n",
                "\n",
                "df_config = pd.DataFrame(config_summary)\n",
                "display(df_config)\n",
                "\n",
                "# ===== COMPREHENSIVE METRICS =====\n",
                "print(\"\\n\" + \"=\" * 100)\n",
                "print(\"📈 COMPREHENSIVE EVALUATION METRICS\")\n",
                "print(\"=\" * 100)\n",
                "\n",
                "# Basic Classification Metrics\n",
                "accuracy = accuracy_score(y_test_final, y_pred_test)\n",
                "precision = precision_score(y_test_final, y_pred_test, average='binary')\n",
                "recall = recall_score(y_test_final, y_pred_test, average='binary')\n",
                "f1 = f1_score(y_test_final, y_pred_test, average='binary')\n",
                "\n",
                "# Confusion Matrix\n",
                "cm_test = confusion_matrix(y_test_final, y_pred_test)\n",
                "tn, fp, fn, tp = cm_test.ravel()\n",
                "\n",
                "# Additional derived metrics\n",
                "specificity = tn / (tn + fp) if (tn + fp) > 0 else 0\n",
                "\n",
                "# Create comprehensive metrics dictionary\n",
                "metrics_dict = {\n",
                "    'Metric': ['Accuracy', 'Precision (PPV)', 'Recall (Sensitivity)', 'Specificity', 'F1 Score'],\n",
                "    'Value': [accuracy, precision, recall, specificity, f1],\n",
                "    'Percentage': [f\"{accuracy*100:.2f}%\", f\"{precision*100:.2f}%\", f\"{recall*100:.2f}%\", f\"{specificity*100:.2f}%\", f\"{f1*100:.2f}%\"],\n",
                "    'Description': ['Overall correctness of predictions', 'Proportion of positive predictions that are correct', 'Proportion of actual positives correctly identified', 'Proportion of actual negatives correctly identified', 'Harmonic mean of precision and recall']\n",
                "}\n",
                "\n",
                "df_metrics = pd.DataFrame(metrics_dict)\n",
                "\n",
                "# Display metrics table\n",
                "print(\"\\n📊 Evaluation Metrics Table:\")\n",
                "display(df_metrics)\n",
                "\n",
                "# ===== CONFUSION MATRIX DETAILS =====\n",
                "print(\"\\n\" + \"=\" * 100)\n",
                "print(\"🔢 CONFUSION MATRIX BREAKDOWN\")\n",
                "print(\"=\" * 100)\n",
                "\n",
                "cm_dict = {\n",
                "    'Category': ['True Negative (TN)', 'False Positive (FP)', 'False Negative (FN)', 'True Positive (TP)'],\n",
                "    'Count': [tn, fp, fn, tp],\n",
                "    'Percentage': [f\"{tn/(tn+fp+fn+tp)*100:.2f}%\", f\"{fp/(tn+fp+fn+tp)*100:.2f}%\", f\"{fn/(tn+fp+fn+tp)*100:.2f}%\", f\"{tp/(tn+fp+fn+tp)*100:.2f}%\"],\n",
                "    'Description': ['Correctly predicted as No Disease', 'Incorrectly predicted as Disease (Type I Error)', 'Incorrectly predicted as No Disease (Type II Error)', 'Correctly predicted as Disease']\n",
                "}\n",
                "\n",
                "df_cm = pd.DataFrame(cm_dict)\n",
                "print(\"\\nConfusion Matrix Components:\")\n",
                "display(df_cm)\n",
                "\n",
                "# ===== CLASSIFICATION REPORT =====\n",
                "print(\"\\n\" + \"=\" * 100)\n",
                "print(\"📋 CLASSIFICATION REPORT (Detailed)\")\n",
                "print(\"=\" * 100)\n",
                "print(classification_report(y_test_final, y_pred_test, target_names=['No Disease', 'Disease']))\n",
                "\n",
                "fig, ax = plt.subplots(1, 1, figsize=(6, 5))\n",
                "sns.heatmap(cm_test, annot=True, fmt='d', cmap='Blues', ax=ax, xticklabels=['No Disease', 'Disease'], yticklabels=['No Disease', 'Disease'])\n",
                "ax.set_xlabel('Predicted')\n",
                "ax.set_ylabel('Actual')\n",
                "ax.set_title('Confusion Matrix - Test Set')\n",
                "plt.tight_layout()\n",
                "plt.show()\n",
                "\n",
                "print(\"\\n\" + \"=\" * 100)\n",
                "print(\"✅ DETAILED EVALUATION MATRIX COMPLETE\")\n",
                "print(\"=\" * 100)\n"
            ]
            
            cell['source'] = new_source
            print('✅ Fixed cell source')
            break

# Write back
with open('Heart_Disease_Analysis_Refactored.ipynb', 'w') as f:
    json.dump(nb, f, indent=1, ensure_ascii=False)

print('✅ Notebook saved')
